global:
  input_source: "video"
  video_path: "videos/snowboard.mp4"
  image_path: "/home/alpon/sample.jpg"
  webcam_index: 0
  show_fps: true
  window_name: "Sixfab | DeepX Python Demo"
  confidence_threshold: 0.5
  iou_threshold: 0.45

demos:
  scrfd:
    model_path: "models/SCRFD500M_1.dxnn"
  yolov10:
    model_path: "models/YOLOV10N-1.dxnn"
  yolov11:
    model_path: "models/YOLOV11N.dxnn"
  yolov12:
    model_path: "models/YOLOV12N-1.dxnn"
  yolov26:
    model_path: "models/yolo26n-1.dxnn"
  yolov26obb:
    model_path: "models/yolo26n-obb.dxnn"
  yolov26pose:
    model_path: "models/yolo26n-pose.dxnn"
  yolov5:
    model_path: "models/YOLOV5S-1.dxnn"
  yolov5face:
    model_path: "models/YOLOV5S_Face-1.dxnn"
  yolov5pose:
    model_path: "models/YOLOV5Pose640_1.dxnn"
  yolov7:
    model_path: "models/YoloV7.dxnn"
  yolov8:
    model_path: "models/YoloV8N.dxnn"
  yolov9:
    model_path: "models/YOLOV9S.dxnn"
  yolox:
    model_path: "models/YOLOX-S_1.dxnn"
  yolov26cls:
    model_path: "models/yolo26n-cls.dxnn"
  deeplabv3:
    model_path: "models/DeepLabV3PlusMobileNetV2_2.dxnn"
  yolov26seg:
    model_path: "models/yolo26n-seg.dxnn"
  yolov8seg:
    model_path: "models/YOLOV8N_SEG-1.dxnn"
  scrfd_ppu:
    model_path: "models/SCRFD500M_PPU.dxnn"
  yolov5_ppu:
    model_path: "models/YOLOV5S_PPU.dxnn"
  yolov5pose_ppu:
    model_path: "models/YOLOV5Pose_PPU.dxnn"
  yolov7_ppu:
    model_path: "models/YoloV7_PPU.dxnn"
  yolov8_async:
    model_path: "models/YoloV8N.dxnn"

  trespassing:
    model_path: "models/yolov8n.dxnn"
    video_path: "videos/snowboard.mp4"
    polygon:
      - [0.313, 0.556]
      - [0.688, 0.556]
      - [0.833, 1.000]
      - [0.167, 1.000]
    confidence_threshold: 0.45
    target_class: "person"
    ultralytics: true
    input_width: 640
    input_height: 640
    decoding_method: "yolo_basic"
    box_format: "center"
    last_activation: "sigmoid"

  people_tracking:
    model_path: "models/YOLOV5S_PPU.dxnn"
    video_path: "videos/mall-complete.mp4"
    confidence_threshold: 0.45
    max_missing_frames: 10
    max_distance: 0.1
    ultralytics: false
    input_width: 512
    input_height: 512
    decoding_method: "yolo_basic"
    box_format: "center"
    last_activation: "sigmoid"
    anchors:
      - stride: 8
        widths:  [10, 16, 33]
        heights: [13, 30, 23]
      - stride: 16
        widths:  [30, 62, 59]
        heights: [61, 45, 119]
      - stride: 32
        widths:  [116, 156, 373]
        heights: [90, 198, 326]

  smart_traffic:
    model_path: "models/yolov8l-ppu.dxnn"
    video_path: "videos/traffic.mp4"
    confidence_threshold: 0.45
    max_missing_frames: 15
    max_match_distance: 0.1
    line: [0.0, 0.6648, 1.0, 0.6648]
    vehicle_classes:
      - "car"
      - "truck"
      - "bus"
      - "motorcycle"
    ultralytics: true
    input_width: 640
    input_height: 640
    decoding_method: "yolo_basic"
    box_format: "center"
    last_activation: "sigmoid"

  store_queue_analysis:
    model_path: "models/yolov8l-ppu.dxnn"
    video_path: "videos/store-queue.mp4"
    confidence_threshold: 0.45
    max_missing_frames: 10
    max_distance: 0.1
    regions:
      - - [0.537, 0.143]
        - [0.625, 0.143]
        - [0.666, 0.501]
        - [0.551, 0.501]
      - - [0.754, 0.139]
        - [0.881, 0.139]
        - [0.972, 0.389]
        - [0.852, 0.389]
      - - [0.328, 0.217]
        - [0.383, 0.217]
        - [0.352, 0.593]
        - [0.273, 0.593]
    wait_thresholds:
      green: 7
      yellow: 15
    ultralytics: true
    input_width: 640
    input_height: 640
    decoding_method: "yolo_basic"
    box_format: "center"
    last_activation: "sigmoid"

  hand_landmark:
    model_path: "models/hand-landmark.dxnn"
    confidence_threshold: 0.3
    iou_threshold: 0.4
    kpt_count: 21
    input_width: 640
    input_height: 640
    landmark_visibility_threshold: 0.5
    input_source: "webcam"

  face_alignment:
    model_path: "models/YOLOV5S_Face-1.dxnn"
    emotion_model_path: "models/efficientnet_affectnet.dxnn"
    input_width: 640
    input_height: 640
    confidence_threshold: 0.25
    iou_threshold: 0.4
    kpt_count: 5
    emotion_input_width: 224
    emotion_input_height: 224
    emotion_classes:
      - "neutral"
      - "happy"
      - "sad"
      - "surprise"
      - "fear"
      - "disgust"
      - "anger"
      - "contempt"
    input_source: "rpicam"

  pose_estimation:
    model_path: "models/YOLOV5Pose_PPU.dxnn"
    input_width: 640
    input_height: 640
    confidence_threshold: 0.15
    iou_threshold: 0.4
    kpt_count: 17
    video_path: "videos/pilates.mp4"

  mask_detection:
    model_path: "models/mask_detection_yolov5_ppu.dxnn"
    input_width: 640
    input_height: 640
    confidence_threshold: 0.3
    iou_threshold: 0.4
    label_classes:
      - "With mask"
      - "Without mask"
      - "Mask weared incorrectly"
    input_source: "webcam"
    webcam_index: 0

  ppe_detection:
    model_path: "models/ppe-detection-v11.dxnn"
    input_width: 640
    input_height: 640
    confidence_threshold: 0.3
    iou_threshold: 0.4
    label_classes:
      - "Hardhat"
      - "Mask"
      - "NO-Hardhat"
      - "NO-Mask"
      - "NO-Safety Vest"
      - "Person"
      - "Safety Cone"
      - "Safety Vest"
      - "Machinery"
      - "Vehicle"
    input_source: "webcam"
    webcam_index: 0

  conveyor_band:
    model_path: "models/conveyor-images-v12.dxnn"
    input_width: 640
    input_height: 640
    confidence_threshold: 0.3
    iou_threshold: 0.4
    label_classes:
      - "cardboard"
      - "glass"
      - "metal"
      - "paper"
      - "plastic"
    video_path: "videos/conveyor-band.mp4"

  privacy_masking:
    model_path: "models/YOLOv5s_512.dxnn"
    input_width: 512
    input_height: 512
    confidence_threshold: 0.3
    iou_threshold: 0.4
    target_classes:
      - "person"
    video_path: "videos/mall2.mp4"
    blur_kernel_size: 51

  multi_channel_4:
    model_path: "models/YOLOv5s_512.dxnn"
    input_width: 512
    input_height: 512
    confidence_threshold: 0.3
    iou_threshold: 0.4
    ultralytics: false
    decoding_method: "yolo_basic"
    box_format: "center"
    last_activation: "sigmoid"
    anchors:
      - stride: 8
        widths:  [10, 16, 33]
        heights: [13, 30, 23]
      - stride: 16
        widths:  [30, 62, 59]
        heights: [61, 45, 119]
      - stride: 32
        widths:  [116, 156, 373]
        heights: [90, 198, 326]
    channels:
      - {source: "video", path: "videos/360p/7_360p.avi"}
      - {source: "video", path: "videos/360p/8_360p.avi"}
      - {source: "video", path: "videos/360p/10_360p.avi"}
      - {source: "video", path: "videos/360p/11_360p.avi"}
